export const GET_QUESTIONS = 'GET_QUESTIONS';
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const REJECT_QUESTION = 'REJECT_QUESTION';
export const VERIFY_PIN = 'VERIFY_PIN';
export const API_FAILURE = 'API_FAILURE';
export const API_SUCCESS = 'API_SUCCESS'; 
export const UPDATE_DOCTOR_PROFILE = 'UPDATE_DOCTOR_PROFILE';
