export const GET_REMINDER_LIST = 'GET_REMINDER_LIST';
export const SET_REMINDER_LIST = 'SET_REMINDER_LIST';
export const UPDATE_REMINDER = 'UPDATE_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';
export const CREATE_REMINDER = 'CREATE_REMINDER';
export const SET_REMINDER = 'SET_REMINDER';
export const GET_REMINDER_LIST_BASED_ON_FILTER = 'GET_REMINDER_LIST_BASED_ON_FILTER';
